### ISSUE TITLE
Проблемы с выводом тренировок

### ISSUE THREAD

**Issue by Karpov760** [Daniil-Solo/Training-tracker#35]
![image](https://user-images.githubusercontent.com/77189625/122877942-9bd1e280-d350-11eb-8b37-8ef044484932.png)
на ветке develop что-то не так

**Comment by Daniil-Solo** [comment]
Сейчас я залью пулл реквест и попробуй снова

**Comment by Daniil-Solo** [comment]
Все работает. Если что-то не так, то убери все пользовательские файлы: my_profile.json, workout.db, my_records.json

**Comment by Karpov760** [comment]
отлично, помогло
